Fs = 8000;
N = 10000;
t = 0:1/Fs:(N-1)/Fs
lo = sin(2*pi*697*t);
hi = cos(2*pi*1209*t);
data = lo + hi;
f = 1209;
freq_indices = round(f*N/Fs);   
dft_data0 = goertzel_classic(data,freq_indices)
dft_data1 = myGoertzel2(data, freq_indices)
dft_data2 = myGoertzel(data, freq_indices)
dft_data3 = goertzel(data, freq_indices)
mag0 = abs(dft_data0)
mag = abs(dft_data1)
mag2 = abs(dft_data2)
magn3 = abs(dft_data3)
ph0 = atan(imag(dft_data)/real(dft_data))
ph1 = atan(imag(dft_data1)/real(dft_data1))
ph2 = atan(imag(dft_data2)/real(dft_data2))
ph3 = atan(imag(dft_data3)/real(dft_data3))
